branches:
  only:
    - master
cache:
  yarn: true
  directories:
    - node_modules
language: node_js
node_js:
  - node
notifications:
  email:
    recipients:
      - ev@haus.gg
script:
  - yarn test
